---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
# spring:
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:9999/uaa/user

